input_dir: ../../INTERSTEPS/STEP_6_TO_7
input_glob: "**/step_6_chunks.chunks.json"
input_sim_run: random
output_format: pkl
output_dir: ../../INTERSTEPS/STEP_7_TO_8
chunk_rows: 100000
plot_sample_rows: true