input_dir: ../../INTERSTEPS/STEP_7_TO_8
input_glob: "**/step_7_chunks.chunks.json"
input_sim_run: random
output_format: pkl
output_dir: ../../INTERSTEPS/STEP_8_TO_9
chunk_rows: 100000
plot_sample_rows: true