# Fixed


# Semifixed
t_fee_sigma_ns: 0.030
charge_threshold: 0.01
q_to_time_factor: 0.00001
qfront_offsets:
  - [85, 87, 89, 91]
  - [86, 88, 90, 92]
  - [87, 89, 91, 93]
  - [88, 90, 92, 94]
qback_offsets:
  - [86, 88, 90, 92]
  - [87, 89, 91, 93]
  - [88, 90, 92, 94]
  - [89, 91, 93, 95]

# Variable (to loop on)