input_dir: ../../INTERSTEPS/STEP_7_TO_8
input_glob: "**/geom_*_calibrated.pkl"
input_sim_run: random
geometry_id: auto
output_format: pkl
output_dir: ../../INTERSTEPS/STEP_8_TO_9
chunk_rows: 100000
plot_sample_rows: true
