input_dir: ../../INTERSTEPS/STEP_4_TO_5
input_glob: "**/step_4_chunks.chunks.json"
input_sim_run: random
output_format: pkl
output_dir: ../../INTERSTEPS/STEP_5_TO_6
chunk_rows: 100000
plot_sample_rows: true