input_dir: ../STEP_7_TO_8
input_glob: "**/geom_*_calibrated.pkl"
input_sim_run: latest
geometry_id: 0
output_format: pkl
output_dir: ../STEP_8_TO_9
charge_threshold: 0.01
t_fee_sigma_ns: 0.01
q_to_time_factor: 0.00001
qfront_offsets:
  - [90, 91, 92, 93]
  - [100, 101, 102, 103]
  - [110, 111, 112, 113]
  - [120, 121, 122, 123]

qback_offsets:
  - [95, 96, 97, 98]
  - [105, 106, 107, 108]
  - [115, 116, 117, 118]
  - [125, 126, 127, 128]
