input_dir: ../STEP_3_TO_4
input_glob: "**/geom_*_avalanche.pkl"
input_sim_run: latest
geometry_id: 0
output_format: pkl
output_dir: ../STEP_4_TO_5
x_noise_mm: 5.0
time_sigma_ns: 0.4
avalanche_width_mm: 40.0
charge_share_points: 2000
width_scale_exponent: 0.1
width_scale_max: 2.0
