input_dir: ../STEP_6_TO_7
input_glob: "**/geom_*_frontback.pkl"
input_sim_run: latest
geometry_id: 0
output_format: pkl
output_dir: ../STEP_7_TO_8

tfront_offsets:
  - [-100, -101, -102, -103]
  - [-110, -111, -112, -113]
  - [-120, -121, -122, -123]
  - [-130, -131, -132, -133]

tback_offsets:
  - [-90, -91, -92, -93]
  - [-80, -81, -82, -83]
  - [-70, -71, -72, -73]
  - [-60, -61, -62, -63]
