input_dir: ../../INTERSTEPS/STEP_3_TO_4
input_glob: "**/geom_*_avalanche.pkl"
input_sim_run: latest
geometry_id: auto
output_format: pkl
output_dir: ../../INTERSTEPS/STEP_4_TO_5
chunk_rows: 50000
plot_sample_rows: true
