input_dir: ../../INTERSTEPS/STEP_3_TO_4
input_glob: "**/step_3_chunks.chunks.json"
input_sim_run: random
output_format: pkl
output_dir: ../../INTERSTEPS/STEP_4_TO_5
chunk_rows: 50000
plot_sample_rows: true