input_dir: ../STEP_1_TO_2
input_sim_run: latest
input_basename: muon_sample_10000000.pkl
station_config_root: /home/mingo/DATAFLOW_v3/MASTER/CONFIG_FILES/ONLINE_RUN_DICTIONARY
geometry_id: 0
output_format: pkl
output_dir: ../STEP_2_TO_3
normalize_to_first_plane: true
c_mm_per_ns: 299.792458
bounds_mm:
  x_min: -150.0
  x_max: 150.0
  y_min: -143.5
  y_max: 143.5
