input_dir: ../../INTERSTEPS/STEP_10_TO_FINAL
input_glob: "**/geom_*_daq.chunks.json"
input_sim_run: all
input_collect: matching
geometry_id: auto
geometry_map_dir: ../../INTERSTEPS/STEP_0_TO_1
geometry_map_sim_run: latest
output_dir: ../../SIMULATED_DATA
chunk_rows: 100000
target_rows: 35000
files_per_station_conf: 5
payload_sampling: sequential_random_start
