input_dir: ../../INTERSTEPS/STEP_10_TO_FINAL
input_glob: "**/step_10_chunks.chunks.json"
input_sim_run: all
input_collect: matching
param_mesh_dir: ../../INTERSTEPS/STEP_0_TO_1
param_mesh_sim_run: none
output_dir: ../../SIMULATED_DATA
chunk_rows: 100000
target_rows: 100000
files_per_station_conf: 1
payload_sampling: sequential_random_start
