input_dir: ../../INTERSTEPS/STEP_5_TO_6
input_glob: "**/step_5_chunks.chunks.json"
input_sim_run: random
output_format: pkl
output_dir: ../../INTERSTEPS/STEP_6_TO_7
chunk_rows: 100000
plot_sample_rows: true