input_dir: ../../INTERSTEPS/STEP_2_TO_3
input_glob: "**/step_2_chunks.chunks.json"
input_sim_run: random
param_mesh_dir: ../../INTERSTEPS/STEP_0_TO_1
param_mesh_sim_run: none
output_format: pkl
output_dir: ../../INTERSTEPS/STEP_3_TO_4
chunk_rows: 100000
plot_sample_rows: true