input_dir: ../STEP_10_TO_11
input_glob: "**/geom_*_daq.pkl"
input_sim_run: latest
geometry_id: 0
output_dir: ../STEP_11_TO_12
event_type: 1
date_mode: now
year: 2024
month: 5
day: 22
hour: 19
minute: 55
second: 43
