n_tracks: 150000000
xlim_mm: 5000
ylim_mm: 5000
z_plane_mm: 100
cos_n: 2
seed: null
c_mm_per_ns: 299.792458
output_format: pkl
output_basename: muon_sample
output_dir: ../../INTERSTEPS/STEP_1_TO_2
chunk_rows: 200000
plot_sample_rows: true
