input_dir: ../../INTERSTEPS/STEP_1_TO_2
input_sim_run: random
input_basename: null
normalize_to_first_plane: true
station_config_root: /home/mingo/DATAFLOW_v3/MASTER/CONFIG_FILES/ONLINE_RUN_DICTIONARY
geometry_map_dir: ../../INTERSTEPS/STEP_0_TO_1
geometry_map_sim_run: latest
output_format: pkl
output_dir: ../../INTERSTEPS/STEP_2_TO_3
chunk_rows: 200000
plot_sample_rows: true
